version: "2.4"
services:
  es:
    image: elasticsearch:6.5.1
    mem_swappiness: 1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      esnet:
        aliases:
          - elasticsearch
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
    volumes:
      - $PWD/data/es:/usr/share/elasticsearch/data

  kibana:
    image: kibana:6.5.1
    networks:
      - esnet
    ports:
      - 5601:5601

networks:
  esnet:
    driver: bridge
